model:
  n_classes: 5

training:
  batch_size: 64
  n_epochs: 50
  lr: 0.001
  augment_factor: 2
  save_dir: "./checkpoints"
  out_dir: "./output"
  val_steps: 10
  data_max_workers: 6

test:
  dir: "./test"
  samples_per_class: 300


dataset:
  folder: "/home/xubiker/dev/PATH-DT-MSU.WSS2"
  layer: 1
  patch_size: 224
  batches_per_worker: 2
  patches_from_one_region: 4
